FROM python:3.12.0
WORKDIR /app
COPY . /app
RUN pip3 install fastapi uvicorn joblib statsmodels loguru typing
EXPOSE 8000
CMD ["uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8000", "--reload"]
